name: Code checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Istall python
        with:
          python-version: 3.8
      - name: Install libs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Flake8
        run: flake8
